# Graph with weight

<img src="http://ege-study.ru/wp-content/uploads/2016/04/%D0%B731.jpg">

In [1]:
import numpy as np

In [3]:
matrix = np.array([
    [1,0,0,1],
    [1,1,0,0],
    [0,1,0,1],
    [0,1,1,0],
    [0,0,1,1],
])

In [4]:
print(matrix)

[[1 0 0 1]
 [1 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 0 1 1]]


In [16]:
y = [2,3,5,7,8]
print("  |A|B|C|D|")
for i,j in zip(range(5),y):
    print("{}|{}".format(j,matrix[i]))

  |A|B|C|D|
2|[1 0 0 1]
3|[1 1 0 0]
5|[0 1 0 1]
7|[0 1 1 0]
8|[0 0 1 1]


<hr>

In [8]:
x = [1, 2, 3]
y = [4, 5, 6]

for i, j in zip(x, y):
    print( str(i) + " / " + str(j))

1 / 4
2 / 5
3 / 6
