#### makhmudov

# Adjacency matrix (Матрица смежности)

In [1]:
import numpy as np

In [5]:
m = np.array([
    [0,1,0,0,1],
    [1,0,1,1,1],
    [0,1,0,1,0],
    [0,1,1,0,1],
    [1,1,0,1,0]
])

In [6]:
print(m)

[[0 1 0 0 1]
 [1 0 1 1 1]
 [0 1 0 1 0]
 [0 1 1 0 1]
 [1 1 0 1 0]]


In [7]:
# adjacency matrix

print("   |1|2|3|4|5|")
j=1
for i in arr:
    print(str(j) +"|",i)
    j+=1

   |1|2|3|4|5|
1| [0 1 0 0 1]
2| [1 0 1 1 1]
3| [0 1 0 1 0]
4| [0 1 1 0 1]
5| [1 1 0 1 0]
